//go:build !ignore_autogenerated

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	k8s "github.com/crd2go/crd2go/k8s"
)

func (in *FlexCluster) DeepCopyInto(out *FlexCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *FlexCluster) DeepCopy() *FlexCluster {
	if in == nil {
		return nil
	}
	out := new(FlexCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FlexClusterList) DeepCopyInto(out *FlexClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FlexCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *FlexClusterList) DeepCopy() *FlexClusterList {
	if in == nil {
		return nil
	}
	out := new(FlexClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *FlexClusterSpec) DeepCopyInto(out *FlexClusterSpec) {
	*out = *in
	if in.ConnectionSecretRef != nil {
		in, out := &in.ConnectionSecretRef, &out.ConnectionSecretRef
		*out = new(k8s.LocalReference)
		**out = **in
	}
	if in.V20250312 != nil {
		in, out := &in.V20250312, &out.V20250312
		*out = new(FlexClusterSpecV20250312)
		(*in).DeepCopyInto(*out)
	}
}

func (in *FlexClusterSpec) DeepCopy() *FlexClusterSpec {
	if in == nil {
		return nil
	}
	out := new(FlexClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexClusterSpecV20250312) DeepCopyInto(out *FlexClusterSpecV20250312) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = new(FlexClusterSpecV20250312Entry)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupId != nil {
		in, out := &in.GroupId, &out.GroupId
		*out = new(string)
		**out = **in
	}
	if in.GroupRef != nil {
		in, out := &in.GroupRef, &out.GroupRef
		*out = new(k8s.LocalReference)
		**out = **in
	}
}

func (in *FlexClusterSpecV20250312) DeepCopy() *FlexClusterSpecV20250312 {
	if in == nil {
		return nil
	}
	out := new(FlexClusterSpecV20250312)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexClusterSpecV20250312Entry) DeepCopyInto(out *FlexClusterSpecV20250312Entry) {
	*out = *in
	out.ProviderSettings = in.ProviderSettings
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = new([]Tags)
		if **in != nil {
			in, out := *in, *out
			*out = make([]Tags, len(*in))
			copy(*out, *in)
		}
	}
	if in.TerminationProtectionEnabled != nil {
		in, out := &in.TerminationProtectionEnabled, &out.TerminationProtectionEnabled
		*out = new(bool)
		**out = **in
	}
}

func (in *FlexClusterSpecV20250312Entry) DeepCopy() *FlexClusterSpecV20250312Entry {
	if in == nil {
		return nil
	}
	out := new(FlexClusterSpecV20250312Entry)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexClusterStatus) DeepCopyInto(out *FlexClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new([]metav1.Condition)
		if **in != nil {
			in, out := *in, *out
			*out = make([]metav1.Condition, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.V20250312 != nil {
		in, out := &in.V20250312, &out.V20250312
		*out = new(FlexClusterStatusV20250312)
		(*in).DeepCopyInto(*out)
	}
}

func (in *FlexClusterStatus) DeepCopy() *FlexClusterStatus {
	if in == nil {
		return nil
	}
	out := new(FlexClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *FlexClusterStatusV20250312) DeepCopyInto(out *FlexClusterStatusV20250312) {
	*out = *in
	if in.BackupSettings != nil {
		in, out := &in.BackupSettings, &out.BackupSettings
		*out = new(DiskGB)
		(*in).DeepCopyInto(*out)
	}
	if in.ClusterType != nil {
		in, out := &in.ClusterType, &out.ClusterType
		*out = new(string)
		**out = **in
	}
	if in.ConnectionStrings != nil {
		in, out := &in.ConnectionStrings, &out.ConnectionStrings
		*out = new(V20250312ConnectionStrings)
		(*in).DeepCopyInto(*out)
	}
	if in.CreateDate != nil {
		in, out := &in.CreateDate, &out.CreateDate
		*out = new(string)
		**out = **in
	}
	if in.GroupId != nil {
		in, out := &in.GroupId, &out.GroupId
		*out = new(string)
		**out = **in
	}
	if in.Id != nil {
		in, out := &in.Id, &out.Id
		*out = new(string)
		**out = **in
	}
	if in.MongoDBVersion != nil {
		in, out := &in.MongoDBVersion, &out.MongoDBVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	out.ProviderSettings = in.ProviderSettings
	if in.ProviderSettings.BackingProviderName != nil {
		in, out := &in.ProviderSettings.BackingProviderName, &out.ProviderSettings.BackingProviderName
		*out = new(string)
		**out = **in
	}
	if in.ProviderSettings.DiskSizeGB != nil {
		in, out := &in.ProviderSettings.DiskSizeGB, &out.ProviderSettings.DiskSizeGB
		*out = new(float64)
		**out = **in
	}
	if in.ProviderSettings.ProviderName != nil {
		in, out := &in.ProviderSettings.ProviderName, &out.ProviderSettings.ProviderName
		*out = new(string)
		**out = **in
	}
	if in.ProviderSettings.RegionName != nil {
		in, out := &in.ProviderSettings.RegionName, &out.ProviderSettings.RegionName
		*out = new(string)
		**out = **in
	}
	if in.StateName != nil {
		in, out := &in.StateName, &out.StateName
		*out = new(string)
		**out = **in
	}
	if in.VersionReleaseSystem != nil {
		in, out := &in.VersionReleaseSystem, &out.VersionReleaseSystem
		*out = new(string)
		**out = **in
	}
}

func (in *FlexClusterStatusV20250312) DeepCopy() *FlexClusterStatusV20250312 {
	if in == nil {
		return nil
	}
	out := new(FlexClusterStatusV20250312)
	in.DeepCopyInto(out)
	return out
}

func (in *V20250312ConnectionStrings) DeepCopyInto(out *V20250312ConnectionStrings) {
	*out = *in
	if in.Standard != nil {
		in, out := &in.Standard, &out.Standard
		*out = new(string)
		**out = **in
	}
	if in.StandardSrv != nil {
		in, out := &in.StandardSrv, &out.StandardSrv
		*out = new(string)
		**out = **in
	}
}

func (in *V20250312ConnectionStrings) DeepCopy() *V20250312ConnectionStrings {
	if in == nil {
		return nil
	}
	out := new(V20250312ConnectionStrings)
	in.DeepCopyInto(out)
	return out
}

func (in *DiskGB) DeepCopyInto(out *DiskGB) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

func (in *DiskGB) DeepCopy() *DiskGB {
	if in == nil {
		return nil
	}
	out := new(DiskGB)
	in.DeepCopyInto(out)
	return out
}
