[
  {
    "op": "add",
    "path": "/spec/versions/0/schema/openAPIV3Schema/properties/status/properties/URL",
    "value": {
      "type": "string"
    }
  },
  {
    "op": "add",
    "path": "/spec/versions/0/schema/openAPIV3Schema/properties/status/properties/mountedWorkspace",
    "value": {
      "type": "string"
    }
  },
  {
    "op": "add",
    "path": "/spec/versions/0/schema/openAPIV3Schema/properties/status/properties/phase",
    "value": {
      "type": "string"
    }
  },
  {
    "op": "add",
    "path": "/spec/versions/0/schema/openAPIV3Schema/properties/status/properties/ready",
    "value": {
      "type": "boolean"
    }
  }
]
